In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.1


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
###Vocablary size is basically the dictionary size
voc_size=10000

One Hot Representation

In [6]:
###One hot encoding you will be getting the indexes from the dictionary
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[7840, 895, 1894, 1885], [7840, 895, 1894, 118], [7840, 7241, 1894, 4402], [9351, 6851, 8032, 5853, 4105], [9351, 6851, 8032, 5853, 9676], [1251, 7840, 2855, 1894, 1695], [6848, 113, 6898, 5853]]


**Word Embedding Representation**

In [7]:
##to make a embedding matrix
###We are using pad_sequences because we want the same number of words in all the sentences. It is very important
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 

In [8]:
import numpy as np

In [9]:
###Here I need to give the sentence length, to which number I want to have the sentence length. Padding is of two types pre and post.
### In pre padding it will add the number in the beginning of the sentence to make the length of the sentence equals to the given sentence length.
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7840  895 1894 1885]
 [   0    0    0    0 7840  895 1894  118]
 [   0    0    0    0 7840 7241 1894 4402]
 [   0    0    0 9351 6851 8032 5853 4105]
 [   0    0    0 9351 6851 8032 5853 9676]
 [   0    0    0 1251 7840 2855 1894 1695]
 [   0    0    0    0 6848  113 6898 5853]]


In [10]:
###dimension is basically the number of features
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451
    0.03667483 -0.00549877 -0.04948603 -0.03890325  0.04641155]
  [-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451
    0.03667483 -0.00549877 -0.04948603 -0.03890325  0.04641155]
  [-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451
    0.03667483 -0.00549877 -0.04948603 -0.03890325  0.04641155]
  [-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451
    0.03667483 -0.00549877 -0.04948603 -0.03890325  0.04641155]
  [ 0.02626443  0.00212573 -0.03544805 -0.01365292 -0.01872882
   -0.03209257  0.04198997 -0.02303906  0.02707073 -0.03718882]
  [-0.01189337  0.02942748 -0.00675587  0.03940735 -0.04827324
   -0.00242122 -0.04230751 -0.03617797 -0.03913634  0.02665074]
  [-0.04355315  0.00958622 -0.01084284  0.03155402  0.00538208
   -0.00062408 -0.04117518 -0.02082646  0.03426815  0.00795294]
  [-0.01432224  0.01792175  0.04304956 -0.03596631  0.03695035
    0.01094458  0.0358316  -0.00658178  0.035153

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7840,  895, 1894, 1885], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451  0.03667483
  -0.00549877 -0.04948603 -0.03890325  0.04641155]
 [-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451  0.03667483
  -0.00549877 -0.04948603 -0.03890325  0.04641155]
 [-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451  0.03667483
  -0.00549877 -0.04948603 -0.03890325  0.04641155]
 [-0.03790371 -0.01560646  0.0192811   0.00901263  0.01148451  0.03667483
  -0.00549877 -0.04948603 -0.03890325  0.04641155]
 [ 0.02626443  0.00212573 -0.03544805 -0.01365292 -0.01872882 -0.03209257
   0.04198997 -0.02303906  0.02707073 -0.03718882]
 [-0.01189337  0.02942748 -0.00675587  0.03940735 -0.04827324 -0.00242122
  -0.04230751 -0.03617797 -0.03913634  0.02665074]
 [-0.04355315  0.00958622 -0.01084284  0.03155402  0.00538208 -0.00062408
  -0.04117518 -0.02082646  0.03426815  0.00795294]
 [-0.01432224  0.01792175  0.04304956 -0.03596631  0.03695035  0.01094458
   0.0358316  -0.00658178  0.0351534   0.02677164]]